export const countries = [
  { name: 'India', flag: '🇮🇳', code: '+91' },
  { name: 'United States', flag: '🇺🇸', code: '+1' },
  { name: 'United Kingdom', flag: '🇬🇧', code: '+44' },
  { name: 'Canada', flag: '🇨🇦', code: '+1' },
  { name: 'Australia', flag: '🇦🇺', code: '+61' },
  { name: 'Germany', flag: '🇩🇪', code: '+49' },
  { name: 'France', flag: '🇫🇷', code: '+33' },
  { name: 'Japan', flag: '🇯🇵', code: '+81' },
  { name: 'Singapore', flag: '🇸🇬', code: '+65' },
  { name: 'United Arab Emirates', flag: '🇦🇪', code: '+971' },
  { name: 'Saudi Arabia', flag: '🇸🇦', code: '+966' },
  { name: 'Netherlands', flag: '🇳🇱', code: '+31' },
  { name: 'Switzerland', flag: '🇨🇭', code: '+41' },
  { name: 'Sweden', flag: '🇸🇪', code: '+46' },
  { name: 'Italy', flag: '🇮🇹', code: '+39' },
  { name: 'Spain', flag: '🇪🇸', code: '+34' },
  { name: 'Brazil', flag: '🇧🇷', code: '+55' },
  { name: 'South Korea', flag: '🇰🇷', code: '+82' },
  { name: 'New Zealand', flag: '🇳🇿', code: '+64' },
  { name: 'South Africa', flag: '🇿🇦', code: '+27' },
  { name: 'Malaysia', flag: '🇲🇾', code: '+60' },
  { name: 'Thailand', flag: '🇹🇭', code: '+66' },
  { name: 'Indonesia', flag: '🇮🇩', code: '+62' },
  { name: 'Philippines', flag: '🇵🇭', code: '+63' },
  { name: 'Bangladesh', flag: '🇧🇩', code: '+880' },
  { name: 'Sri Lanka', flag: '🇱🇰', code: '+94' },
  { name: 'Nepal', flag: '🇳🇵', code: '+977' },
  { name: 'China', flag: '🇨🇳', code: '+86' },
  { name: 'Russia', flag: '🇷🇺', code: '+7' },
]
